version: '1'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./clickhouse:/var/lib/clickhouse

  clickhouse-client:
    image: clickhouse/clickhouse-client:latest
    container_name: clickhouse-client
    hostname: clickhouse-client
    depends_on:
      - clickhouse
    #Wait for clickhouse server to be ready
    entrypoint: ["bash", "-c", "until nc -zv clickhouse 9000; do sleep 1; done && clickhouse-client --host clickhouse"]

    #For connecting via clickhouse-client
    #docker exec -it clickhouse-client bash
    #clickhouse-client --host clickhouse