spring.application.name=spring-clickhouse

server.port=8080

# P6Spy settings
spy.log.file=spy.log
spy.log.format=com.p6spy.engine.spy.appender.CustomLineFormat
spy.log.appender=com.p6spy.engine.spy.appender.Slf4JLogger
spy.log.slf4j.loggerName=p6spy
spy.log.slf4j.markerClass=org.slf4j.MarkerFactory
spy.log.slf4j.marker=SPY
spy.log.rollback=true
spring.sleuth.jdbc.p6spy.enabled=false
logging.level.p6spy=DEBUG

spring.datasource.clickhouse.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
spring.datasource.clickhouse.url=jdbc:clickhouse://127.0.0.1:8123/test_db
spring.datasource.clickhouse.username=default
spring.datasource.clickhouse.database=test_db

logging.level.com.tce.clickhouse=DEBUG
logging.level.org.springframework.security=OFF
logging.level.org.springframework.boot.web.embedded.tomcat.TomcatWebServer=INFO

spring.sql.init.mode=always