appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime) | took %(executionTime)ms | %(category) | connection %(connectionId) | %(sqlSingleLine)
driverlist=cc.blynk.clickhouse.ClickHouseDriver
excludecategories=info,debug,result,resultset,batch,commit
dateformat=yyyy-MM-dd HH:mm:ss a
outagedetection=true
outagedetectioninterval=1